name:                algorithms-roughgarden
version:             0.1.0.0
github:              "tasuki/algorithms-roughgarden"
license:             BSD3
author:              "tasuki"

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  algorithms-roughgarden-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - algorithms-roughgarden
      - hspec >= 2.0.0

executables:
  a1-karatsuba:
    main: A1-karatsuba.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: algorithms-roughgarden
